### ISSUE TITLE
Can't install

### ISSUE THREAD

**Issue by mqewkere** [whoisYeshua/nike-release-checker#2]
I try to do everything according to the instructions, but nothing comes out. Can we contact in the social network?

**Comment by whoisYeshua** [comment]
> I try to do everything according to the instructions, but nothing comes out. Can we contact in the social network?

twitter @YeshuaWhois

**Comment by mqewkere** [comment]
![image](https://user-images.githubusercontent.com/44070557/111032160-b0870c00-842c-11eb-9f88-0e533073c649.png)
I can't write to you

**Comment by whoisYeshua** [comment]
Changed my privacy settings, try again
